import { Octokit } from 'octokit';
import axios from 'axios';

/**
 * Creates a GitHub repository and commits index.html containing the generated web app code.
 *
 * @param {Object} params
 * @param {string} params.repoName - Desired repo name (sanitized)
 * @param {string} params.code - HTML/CSS/JS web app content
 * @param {string} params.token - GitHub personal access token / OAuth token
 * @param {boolean} [params.isPrivate=false] - Whether repo should be private
 * @returns {Promise<{ repoUrl: string, fullRepoName: string, owner: string }>}
 */
export const createRepoAndPushCode = async ({ repoName, code, token, isPrivate = false }) => {
  const githubToken = token || process.env.GITHUB_TOKEN;
  if (!githubToken) {
    throw new Error('GitHub token is required to create a repository.');
  }

  const octokit = new Octokit({ auth: githubToken });

  // 1. Get authenticated user info
  const { data: user } = await octokit.rest.users.getAuthenticated();
  const owner = user.login;

  // Sanitize repo name (alphanumeric, hyphens)
  const sanitizedRepoName = repoName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-_]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || `echo-dev-app-${Date.now()}`;

  let repo;

  // 2. Check if repo already exists, otherwise create it
  try {
    const { data: existingRepo } = await octokit.rest.repos.get({
      owner,
      repo: sanitizedRepoName,
    });
    repo = existingRepo;
  } catch (err) {
    if (err.status === 404) {
      const { data: newRepo } = await octokit.rest.repos.createForAuthenticatedUser({
        name: sanitizedRepoName,
        description: 'Web application generated by ECHO DEV',
        private: isPrivate,
        auto_init: true,
      });
      repo = newRepo;
    } else {
      throw err;
    }
  }

  // 3. Commit/update index.html in the repo
  const filePath = 'index.html';
  const fileContentBase64 = Buffer.from(code || '<!DOCTYPE html><html><body><h1>ECHO DEV App</h1></body></html>').toString('base64');

  let sha;
  try {
    const { data: currentFile } = await octokit.rest.repos.getContent({
      owner,
      repo: repo.name,
      path: filePath,
    });
    if (!Array.isArray(currentFile) && currentFile.sha) {
      sha = currentFile.sha;
    }
  } catch (err) {
    // File doesn't exist yet, sha remains undefined
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo: repo.name,
    path: filePath,
    message: 'Deploy web app via ECHO DEV',
    content: fileContentBase64,
    ...(sha ? { sha } : {}),
  });

  return {
    repoUrl: repo.html_url,
    fullRepoName: repo.full_name,
    owner,
    repoName: repo.name,
  };
};
